# Generated by Django 4.2.1 on 2023-06-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_subject',
            new_name='subject',
        ),
    ]
